/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * 采摘通 API
 * CaiZhaiTong Full Lifecycle Management System API
 * OpenAPI spec version: 1.0
 */

export interface CheckInDto {
  /** 加密的二维码内容 */
  qrContent: string;
  /** 基地ID */
  baseId: number;
}
