/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * 采摘通 API
 * CaiZhaiTong Full Lifecycle Management System API
 * OpenAPI spec version: 1.0
 */

/**
 * 工作周期
 */
export type CreateJobDtoWorkCycle = typeof CreateJobDtoWorkCycle[keyof typeof CreateJobDtoWorkCycle];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateJobDtoWorkCycle = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
} as const;
