/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * 采摘通 API
 * CaiZhaiTong Full Lifecycle Management System API
 * OpenAPI spec version: 1.0
 */

export interface CreateSignupDto {
  /** 基地ID */
  baseId: number;
  /** 岗位ID */
  jobId: number;
  /** 报名日期 (不填默认今天) */
  workDate?: string;
}
