/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * 采摘通 API
 * CaiZhaiTong Full Lifecycle Management System API
 * OpenAPI spec version: 1.0
 */
import type { CreateBaseDtoCategory } from './createBaseDtoCategory';

export interface CreateBaseDto {
  baseName: string;
  /** 营业执照URL */
  licenseUrl: string;
  contactPhone: string;
  category: CreateBaseDtoCategory;
  regionCode: number;
  address?: string;
  description?: string;
}
