/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * 采摘通 API
 * CaiZhaiTong Full Lifecycle Management System API
 * OpenAPI spec version: 1.0
 */

export type CreateBaseDtoCategory = typeof CreateBaseDtoCategory[keyof typeof CreateBaseDtoCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateBaseDtoCategory = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;
