/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * 采摘通 API
 * CaiZhaiTong Full Lifecycle Management System API
 * OpenAPI spec version: 1.0
 */
import type { SysUser } from './sysUser';

export interface LoginResponse {
  /** JWT 访问令牌 */
  access_token: string;
  /** 登录成功的用户信息 */
  user: SysUser;
}
