/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * 采摘通 API
 * CaiZhaiTong Full Lifecycle Management System API
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  /** 手机号，用作登录账号 */
  phone: string;
  /** 身份证后6位（即登录密码） */
  idCardLast6: string;
}
