/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * 采摘通 API
 * CaiZhaiTong Full Lifecycle Management System API
 * OpenAPI spec version: 1.0
 */

/**
 * 用户角色
 */
export type SysUserRoleKey = typeof SysUserRoleKey[keyof typeof SysUserRoleKey];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SysUserRoleKey = {
  super_admin: 'super_admin',
  region_admin: 'region_admin',
  base_manager: 'base_manager',
  field_manager: 'field_manager',
  worker: 'worker',
} as const;
