/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * 采摘通 API
 * CaiZhaiTong Full Lifecycle Management System API
 * OpenAPI spec version: 1.0
 */
import type { SysUserRoleKey } from './sysUserRoleKey';

export interface SysUser {
  /** 数据库唯一ID */
  id: number;
  /** 公开的用户UID */
  uid: string;
  /** 真实姓名 */
  name: string;
  /** 身份证号 (解密后) */
  idCard: string;
  /** 手机号 (解密后) */
  phone: string;
  /** 用户角色 */
  roleKey: SysUserRoleKey;
  /**
   * 头像地址
   * @nullable
   */
  faceImgUrl?: string | null;
  /**
   * 区域代码 (管理员专用)
   * @nullable
   */
  regionCode?: number | null;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
}
