/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * 采摘通 API
 * CaiZhaiTong Full Lifecycle Management System API
 * OpenAPI spec version: 1.0
 */
import type { CreateJobDtoWorkCycle } from './createJobDtoWorkCycle';
import type { CreateJobDtoPayType } from './createJobDtoPayType';

export interface CreateJobDto {
  /** 岗位名称 */
  jobTitle: string;
  /** 招聘人数 */
  recruitCount?: number;
  /** 工作周期 */
  workCycle?: CreateJobDtoWorkCycle;
  /** 工作内容 */
  workContent?: string;
  /** 工作时间 */
  workHours?: string;
  /** 工作开始日期 */
  workStartDate?: string;
  /** 工作结束日期 */
  workEndDate?: string;
  /** 薪资类型: 1-固定, 2-时薪, 3-计件 */
  payType: CreateJobDtoPayType;
  /** 单价（计件或时薪使用） */
  unitPrice?: number;
  /** 固定工资金额 */
  salaryAmount?: number;
  /** 时薪 */
  hourlyRate?: number;
  /** 目标数量（计件用） */
  targetCount?: number;
  /** 招聘要求 */
  requirements?: string;
  /** 最小年龄 */
  minAge?: number;
  /** 最大年龄 */
  maxAge?: number;
  /** 经验要求 */
  experienceRequired?: string;
  /** 体力要求 */
  physicalRequirement?: string;
  /** 福利描述 */
  benefits?: string;
  /** 是否提供住宿 */
  hasAccommodation?: boolean;
  /** 是否提供餐食 */
  hasMeals?: boolean;
  /** 是否有交通补贴 */
  hasTransportation?: boolean;
  /** 交通补贴金额 */
  transportationSubsidy?: number;
  /** 工作场景图片URL数组 */
  workplaceImages?: string[];
  /** 视频URL */
  videoUrl?: string;
  /** 有效期至 */
  validUntil?: string;
  /** 是否自动续期 */
  autoRenew?: boolean;
  /** 续期天数 */
  renewalDays?: number;
}
