/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * 采摘通 API
 * CaiZhaiTong Full Lifecycle Management System API
 * OpenAPI spec version: 1.0
 */

/**
 * 薪资类型: 1-固定, 2-时薪, 3-计件
 */
export type CreateJobDtoPayType = typeof CreateJobDtoPayType[keyof typeof CreateJobDtoPayType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateJobDtoPayType = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;
