/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * 采摘通 API
 * CaiZhaiTong Full Lifecycle Management System API
 * OpenAPI spec version: 1.0
 */

export interface OfflineRecordDto {
  /** 用户UID */
  uid: string;
  /** 基地ID */
  baseId: number;
  /** 签到时间 */
  checkinTime: string;
  /** 工作日期 (YYYY-MM-DD) */
  date?: string;
}
