/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * 采摘通 API
 * CaiZhaiTong Full Lifecycle Management System API
 * OpenAPI spec version: 1.0
 */

export type RecommendationControllerGetRecommendedBasesParams = {
/**
 * 用户当前纬度 (预留)
 */
lat?: number;
/**
 * 用户当前经度 (预留)
 */
lng?: number;
};
