/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * 采摘通 API
 * CaiZhaiTong Full Lifecycle Management System API
 * OpenAPI spec version: 1.0
 */

export interface RecommendationResultDto {
  /** 基地ID */
  id: number;
  /** 基地名称 */
  baseName: string;
  /** 基地类别 */
  categoryName: string;
  /** 区域代码 */
  regionCode: number;
  /** 推荐得分 (0-100) */
  score: number;
  /** 推荐理由列表 */
  matchReasons: string[];
  /** 当前在招岗位数量 */
  activeJobsCount: number;
  /** 封面图 */
  imageUrl?: string;
}
