/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * 采摘通 API
 * CaiZhaiTong Full Lifecycle Management System API
 * OpenAPI spec version: 1.0
 */
import type { OfflineRecordDto } from './offlineRecordDto';

export interface SyncOfflineDto {
  /** 离线签到记录列表 */
  records: OfflineRecordDto[];
}
