CREATE TABLE IF NOT EXISTS `salary_report_submission` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `base_id` bigint NOT NULL COMMENT '基地 ID',
  `boss_id` bigint NOT NULL COMMENT '老板用户 ID',
  `submitted_by` bigint NOT NULL COMMENT '提交人 ID',
  `base_name_snapshot` varchar(100) NOT NULL COMMENT '提交时基地名称快照',
  `boss_name_snapshot` varchar(50) NOT NULL COMMENT '提交时老板名称快照',
  `date_from` date DEFAULT NULL COMMENT '工资表开始日期',
  `date_to` date DEFAULT NULL COMMENT '工资表结束日期',
  `salary_record_count` int NOT NULL DEFAULT '0' COMMENT '纳入工资单数量',
  `worker_count` int NOT NULL DEFAULT '0' COMMENT '工资表工人数',
  `total_income` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '工资表总金额',
  `file_name` varchar(255) NOT NULL COMMENT '工资表文件名',
  `report_payload` longtext NOT NULL COMMENT '工资表快照 JSON',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `IDX_salary_report_submission_base_created` (`base_id`, `created_at`),
  KEY `IDX_salary_report_submission_boss_created` (`boss_id`, `created_at`),
  KEY `IDX_salary_report_submission_submitted_by` (`submitted_by`),
  CONSTRAINT `FK_salary_report_submission_base` FOREIGN KEY (`base_id`) REFERENCES `base_info` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_salary_report_submission_boss` FOREIGN KEY (`boss_id`) REFERENCES `sys_user` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_salary_report_submission_submitter` FOREIGN KEY (`submitted_by`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
